version: '3.8'
services:
  api:
    platform: linux/amd64
    container_name: api
    restart: unless-stopped
    image: helgazhyzhka/homelibrary-api:1.0.0-alpha.1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - db
    environment:
      - PORT=${APP_PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_SECRET_REFRESH_KEY=${JWT_SECRET_REFRESH_KEY}
      - TOKEN_EXPIRE_TIME=${TOKEN_EXPIRE_TIME}
      - TOKEN_REFRESH_EXPIRE_TIME=${TOKEN_REFRESH_EXPIRE_TIME}

    volumes:
      - ./src:/usr/app/src
      - ./logs:/usr/app/logs
    networks:
      - homelibrary
  db:
    platform: linux/amd64
    container_name: db
    restart: unless-stopped
    image: helgazhyzhka/homelibrary-db:1.0.0-alpha.1
    build:
      context: ./db
      dockerfile: Dockerfile.db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-logs:/var/log/postgresql
    networks:
      - homelibrary
volumes:
  db-data:
    driver: local
  db-logs:
    driver: local
networks:
  homelibrary:
    name: ${NETWORK}
    driver: ${DRIVER}
